# Sample Configuration

sampleList:

  ##########################
  # Nue selection
  ##########################

  - name: "#nu_{e} Selec"
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/atm_binning_reco_nueselec.txt"
    selectionCuts: "detNuFlavor==12 && (iniNuFlavor == interNuFlavor || mcIsCC == 1)" 
    dataSets: [ "FD" ]


 ##########################
  # Numu selection
  ##########################

  - name: "#nu_{#mu} Selec"
    isEnabled: true
    binning: "./inputs/samples/binning_DUNE/atm_binning_reco_numuselec.txt"
    selectionCuts: "detNuFlavor==14 && (iniNuFlavor == interNuFlavor || mcIsCC == 1)" 
    dataSets: [ "FD" ]